# Generated by Django 5.0.6 on 2024-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
