# Generated by Django 5.0.6 on 2024-07-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0006_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bacoin',
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('name', 'user')},
        ),
    ]
