# Generated by Django 5.0.6 on 2024-06-30 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logAPI', '0001_initial'),
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnlog',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_logs', to='userAPI.wallet'),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='userAPI.user'),
        ),
        migrations.AddField(
            model_name='spendlog',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_logs', to='userAPI.wallet'),
        ),
    ]
