# Generated by Django 5.0.6 on 2024-07-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAPI', '0004_reminder_frequency_transaction_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('EA', 'Earning'), ('EX', 'Expense')], max_length=2),
        ),
    ]
