# Generated by Django 3.2.25 on 2024-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAPI', '0005_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='frequency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='repeating',
            field=models.CharField(blank=True, choices=[('N', 'Never'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1, null=True),
        ),
    ]
