# Generated by Django 3.2.25 on 2024-07-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAPI', '0006_auto_20240721_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeating',
            field=models.CharField(blank=True, choices=[('N', 'Never'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='repeating',
            field=models.CharField(blank=True, choices=[('N', 'Never'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
    ]
