# Generated by Django 3.2.25 on 2024-07-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAPI', '0007_auto_20240729_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='repeating',
            field=models.CharField(blank=True, choices=[('N', 'Never'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='repeating',
            field=models.CharField(blank=True, choices=[('N', 'Never'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1, null=True),
        ),
    ]
