# Generated by Django 3.2.25 on 2024-07-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logAPI', '0008_auto_20240729_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='repeating',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='repeating',
        ),
    ]
