# Generated by Django 3.2.25 on 2024-07-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logAPI', '0009_auto_20240729_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
    ]
